language: node_js
node_js:
  - "0.10.33"
services:
  - postgresql
addons:
  postgresql: "9.3"
  sauce_connect: true
notifications:
  email: false
script:
  - npm run syntax
  - npm test
before_script:
  - psql -c 'create database evernode_test;' -U postgres
  - cd test/scripts; ./create-db.sh evernode_test; cd ../..;
  - PORT=9001 node server/index.js&
  - sleep 5
after_script:
  - npm run coveralls
  - npm run e2e
env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/evernode_test
    - AWS_BUCKET=mlf-evernode-test
    # AWS_ACCESS_KEY_ID
    - secure: TC0hxrgDFmxuUeghVjVleT6I2NEua1uoCriWsL7WSEOrArkIRTB0utcWNOB6mDzubwvAh+zoJdyA/ClIm4BS6PPjQ6jcJT3MQexY7KBf8usbkGevhzzfW1EZfF64Zrpw4g8X5qf10r7og9Jfq5iuSZp1mHL1FGrJJO/G/hCwmnQ=
    # AWS_SECRET_ACCESS_KEY
    - secure: BaEo4UmeTlwH5ZbimJM7TSCpoKCfXjuPzbtn27JwZJhhpMzQzy1JW3mFKK1MA06iUFQVf67BAaKBMqfQbVNpAHNo4lvjyve6F0U3Yt3kgr0txBrjoDDnCAmH1ArMHcHHhOW5PkET44luuRZmmYdPmgMgEjoW3O8CsFTIQlMQGoU=
    # SAUCE_ACCESS_KEY
    - secure: DSqcrU+oqVha7UJCvOdMCKq5DjPCHqAVNLQnDK1Vt1Fo+mM6CUL51/aLcZE3pLQxlAueetbjgRTiSX3EgdMAb3YP6W79gwhMPtkBu28Tpon/kGvcpszs4wZ/nnsw9UhQIl9ACvKuBS3WPGcIm8tCWP//8FoyMn/fGIQ2R8CKPpc=
    # SAUCE_USERNAME
    - secure: YHRXY2znCgPPHRNrnb8DhfZ3EYB7GMSXkuQDTOpBvv0AJ2cRZX9UJubS/yr7R8ePbcKHL85H077u5NTlPvW887Z3SShlQLLOYopuGIN/hEqDKEQ7tF9NEOHaHfX74v2sve2EeK/N4a1lUV8tt4DVxKYv7IZ0vqhBZ7EgtbGK3gU=
